### ISSUE TITLE
PackagesNotFoundError when using conda create

### ISSUE THREAD

**Issue by robban** [kdmayer/PV4GER#3]
I am having problems installing the environment with conda, do I need to add any additional channels other than the default ones?

The output i am getting is:
>conda create --name PV4GER --file requirements.txt
>Collecting package metadata (current_repodata.json): done
>Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
>Collecting package metadata (repodata.json): done
>Solving environment: failed
>
>PackagesNotFoundError: The following packages are not available from current channels:
>
>  - typing-extensions==3.7.4.3=pypi_0
>  - pytorch==1.5.1=py3.8_0
>  - torchaudio==0.5.1=py38
>  - torchvision==0.6.1=py38_cpu
>
>Current channels:
>
>  - https://conda.anaconda.org/conda-forge/osx-64
>  - https://conda.anaconda.org/conda-forge/noarch
>  - https://repo.anaconda.com/pkgs/main/osx-64
>  - https://repo.anaconda.com/pkgs/main/noarch
>  - https://repo.anaconda.com/pkgs/r/osx-64
>  - https://repo.anaconda.com/pkgs/r/noarch

### My environment is this (MacOS):
>conda --version
>conda 4.9.2
>python --version
>Python 3.8.5

**Comment by kdmayer** [comment]
Hi Robban,

Sorry to hear that you are facing environment issues! I replaced the requirements.txt with an environment.yml, hoping that this will solve your issue.

Please try it out by entering:

    conda env create --file environment.yml
    conda activate pv4ger

If you are still facing an issue, we have three options

1. You re-create the environment manually. Shouldn't be too many packages, mostly geopandas, pytorch, numpy, ...
2. I share a spec-file.txt file with you, so you can re-create the exact same environment as described here: https://docs.conda.io/projects/conda/en/4.6.0/user-guide/tasks/manage-environments.html#building-identical-conda-environments
3. I move the project from a conda environment to poetry.

Let me know,

Kevin

**Comment by robban** [comment]
Hi Kevin, thanks for looking into this, I tried:
`
conda env create --file environment.yml
`
and it ran without errors so that looks like a great solution.

Previously I had just installed the required packages manually. Thank you!
